#!/bin/bash --norc

# Copyright 2023 mjbots Robotic Systems, LLC.  info@mjbots.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# llvm-strip doesn't support the nostdinc++ option
ARGS=()

total=$#
for (( i=1; i<=$(( $total -1 )); i++ ))
do
    var=${!i}
    if [ "$var" == "-nostdinc++" ]; then
        # just skip this one
        :
    elif [ "$var" == "-fno-limit-debug-info" ]; then
        # skip
        :
    elif [[ "$var" == --target=* ]]; then
        # skip
        :
    elif [[ "$var" == --sysroot=* ]]; then
        # skip
        :
    elif [ "$var" == "-isystem" ]; then
        # skip this and the next
        let i++
    elif [ "$var" == "-R" ]; then
        # skip this and the next
        let i++
    else
        ARGS+=("$var")
    fi
done

exec external/org_llvm_clang/bin/llvm-strip "${ARGS[@]}"
